import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const AUDIO_EXT = new Set([".mp3", ".m4a", ".wav", ".ogg", ".flac", ".aac", ".webm"]);
const COVER_EXT = new Set([".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"]);

function listFiles(dir, exts) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isFile() && exts.has(path.extname(e.name).toLowerCase()))
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));
}

function stripExt(name) {
  return name.replace(/\.[^.]+$/, "");
}

function normalize(name) {
  return stripExt(name)
    .toLowerCase()
    .replace(
      /\b(official|lyric|lyrics|video|audio|visualiser|visualizer|sped up|full song|hd)\b/g,
      " ",
    )
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function tokens(s) {
  return new Set(s.split(" ").filter((t) => t.length > 1));
}

function levenshtein(a, b) {
  const m = a.length;
  const n = b.length;
  if (!m) return n;
  if (!n) return m;
  const dp = Array.from({ length: m + 1 }, (_, i) => i);
  for (let j = 1; j <= n; j++) {
    let prev = dp[0];
    dp[0] = j;
    for (let i = 1; i <= m; i++) {
      const tmp = dp[i];
      dp[i] =
        a[i - 1] === b[j - 1]
          ? prev
          : 1 + Math.min(prev, dp[i], dp[i - 1]);
      prev = tmp;
    }
  }
  return dp[m];
}

function similarity(a, b) {
  if (!a || !b) return 0;
  if (a === b) return 1;
  if (a.includes(b) || b.includes(a)) return 0.88;
  const ta = tokens(a);
  const tb = tokens(b);
  let inter = 0;
  for (const t of ta) if (tb.has(t)) inter++;
  const union = ta.size + tb.size - inter;
  const jaccard = union ? inter / union : 0;
  const lev =
    1 - levenshtein(a, b) / Math.max(a.length, b.length, 1);
  return Math.max(jaccard, lev * 0.65);
}

function parseAudioFilename(filename) {
  let stem = stripExt(filename);
  stem = stem.replace(/\((official|lyric|lyrics|audio|video)[^)]*\)/gi, " ").trim();

  const parts = stem.split(/\s+-\s+/);
  if (parts.length >= 2) {
    const left = parts[0].replace(/\s+/g, " ").trim();
    const rightRaw = parts.slice(1).join(" - ").trim();
    const movieRip =
      /\s{2,}/.test(rightRaw) ||
      (rightRaw.includes(",") && rightRaw.length > left.length * 2);
    let right = rightRaw
      .replace(/\s+(sped up|lyrics|official.*)$/i, "")
      .replace(/\s+/g, " ")
      .trim();

    if (movieRip) {
      const artist = rightRaw.split(/\s{2,}|,/)[0].replace(/\s+/g, " ").trim();
      return { title: left, artist: artist || "Unknown" };
    }
    if (left && right) return { title: right, artist: left };
  }

  let title = stem.replace(/\s+(sped up|lyrics|official.*)$/i, "").replace(/\s+/g, " ").trim();
  return { title: title || filename, artist: "Unknown" };
}

function matchCovers(audioNames, coverNames) {
  const covers = coverNames.map((name) => ({
    name,
    key: normalize(name),
    used: false,
  }));

  const assigned = new Array(audioNames.length).fill("");

  audioNames.forEach((audioName, i) => {
    const key = normalize(audioName);
    let best = -1;
    let bestScore = 0.34;
    covers.forEach((cover, j) => {
      if (cover.used) return;
      const score = similarity(key, cover.key);
      if (score > bestScore) {
        bestScore = score;
        best = j;
      }
    });
    if (best >= 0) {
      covers[best].used = true;
      assigned[i] = `/covers/${covers[best].name}`;
    }
  });

  const leftovers = covers.filter((c) => !c.used);
  let li = 0;
  assigned.forEach((cover, i) => {
    if (!cover && leftovers[li]) {
      assigned[i] = `/covers/${leftovers[li].name}`;
      li += 1;
    }
  });

  return assigned;
}

function escapeTs(str) {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function generateSongs(root = process.cwd()) {
  const audioDir = path.join(root, "public", "audio");
  const coverDir = path.join(root, "public", "covers");
  const outFile = path.join(root, "src", "songs.generated.ts");

  const audioNames = listFiles(audioDir, AUDIO_EXT);
  const coverNames = listFiles(coverDir, COVER_EXT);
  const covers = matchCovers(audioNames, coverNames);

  const songs = audioNames.map((name, i) => {
    const { title, artist } = parseAudioFilename(name);
    return {
      title,
      artist,
      src: `/audio/${name}`,
      cover: covers[i] || "",
    };
  });

  const body = songs
    .map(
      (s) => `  {
    title: "${escapeTs(s.title)}",
    artist: "${escapeTs(s.artist)}",
    src: "${escapeTs(s.src)}",
    cover: "${escapeTs(s.cover)}",
  }`,
    )
    .join(",\n");

  const contents = `// AUTO-GENERATED by scripts/generate-songs.mjs — do not edit.
// Drop files into public/audio/ and public/covers/, then restart (or save) to refresh.

export interface Song {
  title: string;
  artist: string;
  src: string;
  cover: string;
}

export const songs: Song[] = [
${body}
];
`;

  const prev = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : "";
  if (prev !== contents) {
    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, contents);
    console.log(`[songs] generated ${songs.length} track(s) from public/audio`);
  }

  return songs;
}

const isDirectRun = process.argv[1]
  ? path.resolve(fileURLToPath(import.meta.url)) === path.resolve(process.argv[1])
  : false;

if (isDirectRun) {
  generateSongs();
}
