// AUTO-GENERATED by scripts/generate-songs.mjs — do not edit.
// Drop files into public/audio/ and public/covers/, then restart (or save) to refresh.

export interface Song {
  title: string;
  artist: string;
  src: string;
  cover: string;
}

export const songs: Song[] = [
  {
    title: "Safar",
    artist: "Bayaan & Sherazam",
    src: "/audio/Bayaan & Sherazam - Safar.mp3",
    cover: "/covers/ -6.jpg",
  },
  {
    title: "Blackbear",
    artist: "hot girl bummer",
    src: "/audio/Blackbear - hot girl bummer  sped up  lyrics.mp3",
    cover: "/covers/1037939045389576829.jpg",
  },
  {
    title: "Perfect",
    artist: "Ed Sheeran",
    src: "/audio/Ed Sheeran - Perfect.mp3",
    cover: "/covers/1041387113928838553.jpg",
  },
  {
    title: "Heat Waves",
    artist: "Glass Animals",
    src: "/audio/Glass Animals - Heat Waves (Official Video).mp3",
    cover: "/covers/1075304848539893076.jpg",
  },
  {
    title: "Gym Class Heroes_ Stereo Hearts ft. Adam Levine [OFFICIAL VIDEO]",
    artist: "Unknown",
    src: "/audio/Gym Class Heroes_ Stereo Hearts ft. Adam Levine [OFFICIAL VIDEO].mp3",
    cover: "/covers/1101763496397931579.jpg",
  },
  {
    title: "HALKA HALKA Full Audio Song Rahat Fateh Ali Khan Feat. Ayushmann Khurrana & Amy Jackson T-Series",
    artist: "Unknown",
    src: "/audio/HALKA HALKA Full Audio Song  Rahat Fateh Ali Khan Feat. Ayushmann Khurrana & Amy Jackson  T-Series.mp3",
    cover: "/covers/354025220729905820.jpg",
  },
  {
    title: "Kabira Encore",
    artist: "Yeh Jawaani Hai Deewani",
    src: "/audio/Kabira Encore - Yeh Jawaani Hai Deewani  Ranbir Kapoor, Deepika Padukone.mp3",
    cover: "/covers/384565255702107763.jpg",
  },
  {
    title: "Kabira Full Song Yeh Jawaani Hai Deewani Pritam Ranbir Kapoor, Deepika Padukone",
    artist: "Unknown",
    src: "/audio/Kabira Full Song Yeh Jawaani Hai Deewani  Pritam  Ranbir Kapoor, Deepika Padukone.mp3",
    cover: "/covers/573646071307116229.jpg",
  },
  {
    title: "Lag Ja Gale Ki Phir Ye Haseen Raat Ho Na Ho Video Song Lata Mangeshkar Woh Kaun Thi Songs",
    artist: "Unknown",
    src: "/audio/Lag Ja Gale Ki Phir Ye Haseen Raat Ho Na Ho Video Song  Lata Mangeshkar  Woh Kaun Thi Songs.mp3",
    cover: "/covers/642114859417697153.jpg",
  },
  {
    title: "Night Changes",
    artist: "One Direction",
    src: "/audio/One Direction - Night Changes.mp3",
    cover: "/covers/901845894194353736.jpg",
  },
  {
    title: "Rain (Long Version)",
    artist: "Unknown",
    src: "/audio/Rain (Long Version).mp3",
    cover: "/covers/924012048598122312.jpg",
  },
  {
    title: "Line Without a Hook",
    artist: "Ricky Montgomery",
    src: "/audio/Ricky Montgomery - Line Without a Hook (Official Lyric Video).mp3",
    cover: "/covers/951878071266097918.jpg",
  },
  {
    title: "Rough Days",
    artist: "Unknown",
    src: "/audio/Rough Days.mp3",
    cover: "/covers/cat on sea.jpg",
  },
  {
    title: "I Thought I Saw Your Face Today",
    artist: "She & Him",
    src: "/audio/She & Him - I Thought I Saw Your Face Today (Official Lyric Video).mp3",
    cover: "/covers/Cute cat icon__🎧.jpg",
  },
  {
    title: "SugarCrash!",
    artist: "Unknown",
    src: "/audio/SugarCrash!.mp3",
    cover: "/covers/Surf cat.jpg",
  }
];
